### ISSUE TITLE
error mounting

### ISSUE THREAD

**Issue by killer1500nw** [oblivioncth/FIL#23]
So Ive downloaded the lastest Flashpoint this week, and successfully used the import tool to get it into Launchbox with the latest version here of both FIL and  CLIFp, all freshly downloaded this week.
The import process went fine, but in Launchbox it it doesn't work and comes up with a mounting error for all flash files.
![2023-04-28 (214)](https://user-images.githubusercontent.com/112395612/235089968-04bf3a24-df2f-46ed-9ad6-bd5ce2a85ecf.png)

**Comment by killer1500nw** [comment]
Yeah anything in the Flash section doesn't work, not just TCL, that was just the last playlist I tried to play for the screenshot. 
CLIFp.exe is 0.9.4 and Flashpoint is 11.1 (and works fine stand-alone). I doubled check CLFIp.exe in Windows, and Flashpoint showed me the version in the txt file in the root, again all freshly downloaded this week the latest versions. 

I was using an older version of Flashpoint fine in my collection (was version 10.1) but decided to upgrade, so deleted all the old playlists in LB, etc, re-downloaded the latest Flashpoint and new versions of the import tool and everything went through as expected. 

PC specs are 
AMD Ryzen 7 5700G
32 Gigs of Ram 
AMD RX 6600 3.80Ghz
Seagate 16tb Exos Sata X18 drive. 
Windows 10 Pro Version 22H2
Flashpoint 11.1 Ultimate - "Operation Cherry Blossom" 
CLIFp 0.9.4 Static




[CLIFp.log](https://github.com/oblivioncth/FIL/files/11357722/CLIFp.log)

**Comment by oblivioncth** [comment]
I think this is likely an Ultimate specific problem and I don't currently have a copy of 11.1 myself to test with. I just started downloading it, but of course it will take a while before it's finished and I can try to reproduce the issue.

**Comment by oblivioncth** [comment]
Actually, when you get a chance if you could upload a copy of "[Flashpoint Root]/Data/services.json" from Ultimate 11.1 that would be great.

**Comment by killer1500nw** [comment]
Here is a copy of my  services.json

**Comment by killer1500nw** [comment]
[services.zip](https://github.com/oblivioncth/FIL/files/11359014/services.zip)

**Comment by oblivioncth** [comment]
Ah, the random minor nonsensical differences between the editions and versions of Flashpoint.

The same exact thing is named differently between Infinity and Ultimate it seems and I didn't catch that when I recently changed how part of the configuration is read.

When I can get back to my PC I'll release a fix.

**Comment by oblivioncth** [comment]
I can't test it myself at a moment but replace your copy of CLIFp with this specific build and let me know if it works: https://github.com/oblivioncth/CLIFp/suites/12579933733/artifacts/672694390

**Comment by oblivioncth** [comment]
Ok, I got a chance to examine this directly myself and this issue has now been fixed by https://github.com/oblivioncth/CLIFp/pull/58 
and will be included in the next release.

[This dev build](https://github.com/oblivioncth/CLIFp/suites/12655626402/artifacts/678241068) includes the fix if you want it a little early. Feel free to reopen this if you still have issues.
