### ISSUE TITLE
[BUG] FIL crash on Launchbox install location selection

### ISSUE THREAD

**Issue by BugByte14** [oblivioncth/FIL#60]
**Describe the bug**
When selecting the install location for my front-end (Launchbox v13.16), FIL freezes for about a second then automatically crashes. I have tried selecting the launchbox location via Explorer and by manually typing out the location, but to no avail. Additionally, I have tried selecting the flashpoint install location (which functions normally) first, but had no luck with that either.

**To Reproduce**
1. Launch FIL as normal.
2. Click on '...' under "Frontend Install:"
3. Navigate to and select the directory of Launchbox install location.
4. FIL freezes for a second then crashes.

**Expected behavior**
Upon selecting the Launchbox install location, the application should continue performing as normal and show up as "Launchbox".

**Version (please complete the following information):**
- FIL version 0.7.5.3
- Flashpoint version 13 (Ultimate)

**Additional context**
I have additionally tried running the application as administrator and in compatibility mode, but had no luck. Additionally, the issue only arises when selecting that directory, it does not crash when I select another directory.

**Comment by BugByte14** [comment]
I'd like to add, I just tried doing it again after making a fresh install of Launchbox onto a different drive and the issue remained.

**Comment by oblivioncth** [comment]
Sorry about that. There was a fix for that issue during development that was supposed to make it in before the last release, but I guess I screwed that up.

Please try again with v0.7.5.4

**Comment by BugByte14** [comment]
The update did resolve that initial issue, but now it crashes during importing even for the new install. I've screenshotted the settings that cause it to crash. It seems to always fail at the 20% mark when it begins "Importing games and additional apps for platform X". This seems to happen regardless of which platforms are selected.

![Screenshot 2024-10-17 185416](https://github.com/user-attachments/assets/b439c8dd-d0c1-42d3-bd52-8142cdd53117)

**Comment by BugByte14** [comment]
Also I just noticed that the program appears to close before completing the writing of the platform xml files leading to corruption. Luckily the backups it creates are still good

**Comment by oblivioncth** [comment]
Gah, I really did 0.7.5.3 in too much of a rush. Another silly oversight.

Try the Windows artifact from this build and let me know if it works for you. 

https://github.com/oblivioncth/FIL/actions/runs/11396198892. I have a full import going in Debug mode overnight just in case, but I believe that change should do it.

**Comment by oblivioncth** [comment]
The changes are in 0.7.5.5. if you want to just use that instead directly. The brief testing I could do shows that it should be fine now.
